language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: Z5sJ8sOdvaYrZNdizfbMPCt5pyA8AcbMJpbnR/DsLyo3LpJepfG8KRgI9mB2wfGhmyFI18alTDGa9yk5jkXrZ/ZU8gUOQWulszht4QaaXjNumdqwskyXg2PFJjeg7nTsywMk6neanQYsZDGJVAzR9v7cxfn1ZAsjgVyQPCxc8oGcMnexeQht1WvJsVmnaUlN47GX14Ga7Tv38XBCX5vZ+2n4S0gBDtvi/o8JR9Goi/+BOIWCZfuhN7EcLver//fLj+EL6ndA1nj9RkMdkKjC2Msezbwpuz3uJqYA1ZE28dAEBwDCtceptcXtphNiWZx/kN0gnZS87V0bXhyWmGJ8tFTNwhwfgS7zgnDw4arFmHuFMbtIco8OX3l4/FVmlYz90nTs7MNrlVAaeRF45ZcXhZmtlmg228fgSKuyqYAX3cikcoC2lvGQhLOs/FWqistB4tShxUPTallYAaQGV7YlnGoQiUx0TmYJ27k2FxtdbAoGafC9Ag6dJbqbdHixCEAq9ix2nxkREbWU/rwXg7GawdY78TE1JdRAd/4ye6lmPog2h0d2nN40GcPxm59a9Vcb42FBcaAhPgujwT6XIJTbVFJmbrhCBUTlAX/ImAB/rFapwDfaANIsjSIjukucfmhkqQ1EcKEW5Q/hejP5/q1Pxhm9W7zOF7f9ubyHEeGESuI=
